<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Nirbhay</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="IT Company Website Template" name="keywords">
        <meta content="IT Company Website Template" name="description">

        <!-- Favicon -->
        <link href="img/fevicon.png" rel="icon">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:200,300,400,500,600,700,800,900&display=swap" rel="stylesheet"> 

        <!-- Libraries CSS -->
        <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet">
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

        <!-- Main Stylesheet -->
        <link href="css/style.css" rel="stylesheet">
    </head>

    <body>
        <!-- Nav Start -->
        <?php include_once("header.php"); ?> 

        <!-- Nav End -->

     <!-- About Start-->
  <div class="about mt-100">
    <div class="container">
        <div class="section-header">
            <h2>All about Password</h2>
            <p>
                Everything You Need to Know About Passwords</p>                </div>
        
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="about-img">
                    <img src="img/3.png" alt="" class="img-fluid">

                </div>
                    <div class="about-content">
                        <h3>All About Password</h3>
                        <br/>
                        
                        <ul>
                           <h5><strong>What is Password:</strong></h5>
                            <li><i class="bi bi-check2-circle"></i>A password is a secret or confidential sequence of characters, typically used to authenticate or verify the identity of a user during the process of accessing a computer system, online account, or secured resource. Passwords play a crucial role in securing digital information and ensuring that only authorized individuals have access to specific services or data.</li></br>
                        </ul>
                        </br></br>
                        
                        <ul>
                           <h5><strong>Types of Password:</strong></h5>
                            <li><i class="bi bi-check2-circle"></i> <strong>Alphanumeric Passwords:</strong>These passwords include a combination of letters (both uppercase and lowercase) and numbers.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Complex Passwords: </strong>These passwords incorporate a mix of uppercase and lowercase letters, numbers, and special characters.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Passphrases: </strong>A passphrase is a sequence of words or other text elements that create a longer but potentially easier-to-remember password. Passphrases are often more secure than shorter, complex passwords.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Biometric Passwords: </strong>Authentication based on biometric data, such as fingerprints, iris scans, or facial recognition.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>PIN (Personal Identification Number): </strong>A numeric password, often used with ATM cards or mobile devices.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>One-Time Password (OTP): </strong>A password that is valid for only one login session or transaction, usually generated by a token or sent to a user's mobile device.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Pattern Lock:</strong>A method of authentication on mobile devices where users create a specific pattern by connecting dots on a grid.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Multi-Factor Authentication (MFA): </strong>Combines two or more different authentication factors (e.g., password, fingerprint, security token) to enhance security.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Password Hash: </strong>Rather than storing actual passwords, many systems store a hash (a one-way function) of the password. This adds an extra layer of security, as the actual password isn't stored in the system.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Two-Factor Authentication (2FA): </strong>Requires two different authentication factors for access, typically something you know (password) and something you have (like a mobile device for receiving codes).</li></br>
                        </ul>
                        <br/><br/>
                        
                        <ul>
                            <h5><strong>Weak Password:</strong></h5>
                              <li><i class="bi bi-check2-circle"></i> <strong>Short Length: </strong>Short passwords are generally weaker. The longer the password, the more difficult it is to crack.</li></br>
                              <li><i class="bi bi-check2-circle"></i> <strong>Common Words or Phrases: </strong>Using easily guessable words, common phrases, or dictionary words makes a password weak.</li></br>
                              <li><i class="bi bi-check2-circle"></i> <strong>Lack of Complexity: </strong>Weak passwords often lack a mix of uppercase and lowercase letters, numbers, and special characters.</li></br>
                              <li><i class="bi bi-check2-circle"></i> <strong>Personal Information: </strong>Avoid using easily obtainable information like names, birthdays, or common words associated with you.</li></br>
                              <li><i class="bi bi-check2-circle"></i> <strong>Sequences or Patterns: </strong>Sequential numbers, letters, or keyboard patterns (e.g., "123456," "qwerty") are weak and easily guessable.</li></br>
                              <li><i class="bi bi-check2-circle"></i> <strong>Repeating Characters: </strong>Repeating the same characters, such as "aaaaaa" or "123123," weakens the password.</li></br>
                        </ul>
                        <br/><br/>
                        
                        <ul>
                          <h5><strong>Strong Password:</strong></h5>
                            <li><i class="bi bi-check2-circle"></i> <strong>Longer Length:  </strong>A longer password is generally more secure. Aim for a minimum of 12 characters or more.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Mix of Characters:  </strong>Include a combination of uppercase and lowercase letters, numbers, and special characters to enhance complexity.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Randomness:  </strong>Create passwords that are not easily guessable and lack patterns. Randomness adds to the strength.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Avoid Common Words:  </strong>Steer clear of easily guessable words or phrases. Use a mix of unrelated words or create a passphrase.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Unique for Each Account:  </strong>Avoid using the same password across multiple accounts. If one password is compromised, it won't jeopardize other accounts.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Regular Updates:  </strong>Change passwords periodically to reduce the risk of compromise.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Use Passphrases:  </strong>Consider using a passphrase—a sequence of words or a sentence—that is both easy to remember and secure.</li></br>
                            <li><i class="bi bi-check2-circle"></i> <strong>Multi-Factor Authentication (MFA):  </strong>Enable MFA whenever possible to add an extra layer of security.</li></br>
                        </ul>
                        <br/><br/>
                        
                        <ul>
                          <h5><strong>How crate strong password:</strong></h5>
                          <li><i class="bi bi-check2-circle"></i> <strong>1.	Length Matters:</strong>Aim for a minimum of 12 characters.Longer passwords are generally more secure.</li></br>
                          <li><i class="bi bi-check2-circle"></i> <strong>2.	Use a Mix of Characters:</strong>Include uppercase and lowercase letters.Integrate numbers and special characters (e.g., !, @, #, $).</li></br>
                          <li><i class="bi bi-check2-circle"></i> <strong>3.	Avoid Common Words and Phrases:</strong>Steer clear of dictionary words, names, and easily guessable phrases.Consider using a combination of unrelated words or create a passphrase.</li></br>
                          <li><i class="bi bi-check2-circle"></i> <strong>4.	Randomness is Key:</strong>Avoid using predictable patterns or sequences.Make your password as random as possible.</li></br>
                          <li><i class="bi bi-check2-circle"></i> <strong>5.	Unique for Each Account:</strong>Use different passwords for each of your accounts.This ensures that if one password is compromised, others remain secure.</li></br>
                          <li><i class="bi bi-check2-circle"></i> <strong>6.	Passphrases:</strong>Create a passphrase by stringing together a sequence of words.Make it easy for you to remember but hard for others to guess.</li></br>
                          <li><i class="bi bi-check2-circle"></i> <strong>7.	Avoid Personal Information:</strong>Do not use easily obtainable information, such as your name, birthdate, or addresses.Hackers often try to exploit personal details.</li></br>
                          <li><i class="bi bi-check2-circle"></i> <strong>8.	Regularly Update Your Passwords:</strong>Change your passwords periodically to enhance security.Avoid using the same password for an extended period.</li></br>
                          <li><i class="bi bi-check2-circle"></i> <strong>9.	Consider Using a Password Manager:</strong>Use a reputable password manager to generate and store complex passwords for each account.Password managers can help you keep track of multiple strong passwords without having to remember them all.</li></br>
                        </ul>
                        <br/><br/>
                        
                    </div> 
            </div>
        </div>
    </div>
</div>


 <!-- Footer Start -->
 <?php include_once("footer.php"); ?> 

<!-- Footer End -->

        <a href="#" class="back-to-top"><i class="ion-ios-arrow-up"></i></a>

        <!-- Libraries JS -->
        <script src="lib/jquery/jquery.min.js"></script>
        <script src="lib/jquery/jquery-migrate.min.js"></script>
        <script src="lib/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/counterup/counterup.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/lightbox/js/lightbox.min.js"></script>

        <!-- Main Javascript -->
        <script src="js/main.js"></script>

    </body>
</html>
